import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Tab = 'articles' | 'events' | 'sources' | 'llm' | 'settings'
type DrawerTab = 'overview' | 'content' | 'json'
type Analysis = { importance_score:number; novelty_score:number; confidence:number; market_impact:string; sentiment:string; event_type:string; event_title:string; summary_vi:string; summary_en:string; affected_tickers:string[]; affected_sectors:string[]; affected_assets:string[]; key_facts:unknown[]; new_information:unknown[]; raw_json:unknown }
type Article = { id:string; source_key:string; source_name:string; title:string; excerpt?:string; content_text?:string; content_html?:string; canonical_url?:string; published_at?:string; fetched_at:string; status:string; is_outdated:boolean; time_confidence:string; word_count?:number; processing_error?:string; analysis?: Analysis; cluster?: {id:string; event_title:string; event_type:string; relation:string; update_count:number}; duplicate?: unknown }
type Cluster = { id:string; event_title:string; event_type:string; status:string; importance_score:number; novelty_score:number; affected_tickers:string[]; affected_sectors:string[]; affected_assets?:string[]; article_count:number; update_count:number; source_count:number; last_updated_at:string; summary_en?:string; summary_vi?:string }
type SourceHealth = { key:string; name:string; type:string; enabled:boolean; credibility_score:number; crawl_interval_minutes:number; health:string; last_started_at?:string; last_fetched_count?:number; last_inserted_raw_count?:number; last_inserted_article_count?:number; last_no_fresh_reason?:string; last_quality_rejected_count?:number; last_older_than_window_count?:number; last_candidate_links?:number; last_error?:string }
type CrawlState = { loading:boolean; message?:string; error?:string }

const API = import.meta.env.VITE_API_BASE || ''

async function getJSON<T>(path:string): Promise<T> { const r = await fetch(API + path); if(!r.ok) throw new Error(await r.text()); return r.json() }
async function postJSON<T>(path:string, body?:unknown): Promise<T> { const r = await fetch(API + path,{method:'POST',headers:{'Content-Type':'application/json'},body: body ? JSON.stringify(body) : undefined}); if(!r.ok) throw new Error(await r.text()); return r.json() }
function qs(p:Record<string,string|number|boolean|undefined>) { const q = new URLSearchParams(); Object.entries(p).forEach(([k,v])=>{ if(v!==undefined && v!=='') q.set(k,String(v)) }); return q.toString() }

function App(){
  const [tab,setTab]=useState<Tab>((new URLSearchParams(location.search).get('tab') as Tab)||'articles')
  const [stats,setStats]=useState<any>({})
  const [q,setQ]=useState('')
  const [fresh,setFresh]=useState(true)
  const [impact,setImpact]=useState('')
  const [eventType,setEventType]=useState('')
  const [ticker,setTicker]=useState('')
  const [source,setSource]=useState('')
  const [page,setPage]=useState(1)
  const [selected,setSelected]=useState<Article|Cluster|null>(null)
  const [refreshKey,setRefreshKey]=useState(0)
  const [crawl,setCrawl]=useState<CrawlState>({loading:false})
  const filters={q, fresh_only:fresh, impact, event_type:eventType, ticker, source, page, page_size:50}
  const refresh=()=>setRefreshKey(x=>x+1)

  useEffect(()=>{getJSON('/api/stats').then(setStats).catch(()=>setStats({}))},[refreshKey])
  useEffect(()=>{ const u=new URL(location.href); u.searchParams.set('tab',tab); history.replaceState(null,'',u)},[tab])
  useEffect(()=>{
    if ((stats.llm_pending??0) <= 0 && !crawl.loading) return
    const id=window.setInterval(refresh,3000)
    return()=>window.clearInterval(id)
  },[stats.llm_pending,crawl.loading])

  async function triggerCrawl(sourceKey?:string){
    const label=sourceKey?` for ${sourceKey}`:''
    setCrawl({loading:true,message:`Starting crawl${label}...`})
    try{
      await postJSON('/api/admin/crawl-once', sourceKey?{source_key:sourceKey}:{})
      setCrawl({loading:false,message:`Crawl started${label}. Auto-refresh is watching the queue.`})
      refresh()
      window.setTimeout(refresh,2500)
      window.setTimeout(refresh,8000)
    }catch(e){
      setCrawl({loading:false,error:String(e)})
    }
  }
  async function retryFailedLLM(){
    setCrawl({loading:true,message:'Retrying failed LLM jobs...'})
    try{
      const res=await postJSON<{reset:number}>('/api/admin/retry-failed-llm')
      setCrawl({loading:false,message:`Reset ${res.reset} failed LLM job(s).`})
      refresh()
    }catch(e){
      setCrawl({loading:false,error:String(e)})
    }
  }

  return <div className="app"><Header stats={stats} onCrawl={()=>triggerCrawl()} crawl={crawl}/><Tabs tab={tab} setTab={setTab}/>{(tab==='articles'||tab==='events')&&<FilterBar {...{q,setQ,fresh,setFresh,impact,setImpact,eventType,setEventType,ticker,setTicker,source,setSource,page,setPage}}/>}<CrawlStatus state={crawl}/><main>{tab==='articles'&&<Articles filters={filters} refreshKey={refreshKey} onSelect={setSelected}/>} {tab==='events'&&<Events filters={filters} refreshKey={refreshKey} onSelect={setSelected}/>} {tab==='sources'&&<Sources refreshKey={refreshKey} onCrawl={triggerCrawl} crawl={crawl}/>} {tab==='llm'&&<LLMQueue refreshKey={refreshKey}/>} {tab==='settings'&&<Settings onCrawl={()=>triggerCrawl()} onRetryLLM={retryFailedLLM} crawl={crawl}/>}</main>{selected&&<Drawer item={selected} onClose={()=>setSelected(null)}/>}</div>
}
function Header({stats,onCrawl,crawl}:{stats:any;onCrawl:()=>void;crawl:CrawlState}){ return <header><div className="brand"><div className="brand-mark">MS</div><div><h1>MarketSignal</h1><p>Fresh U.S. financial news intelligence · auto-updated every 10m</p><div className="header-actions"><button className="primary" disabled={crawl.loading} onClick={onCrawl}>{crawl.loading?'Crawling...':'Crawl now'}</button>{(stats.llm_pending??0)>0&&<span className="live-dot">LLM queue live</span>}</div></div></div><div className="stats">{[['Fresh',stats.fresh_articles],['Events',stats.active_events],['High impact',stats.high_impact],['LLM pending',stats.llm_pending],['Source errors',stats.source_errors]].map(([k,v])=><div className="pill" key={k}><b>{v??0}</b><span>{k}</span></div>)}</div></header> }
function Tabs({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){ const tabs:[Tab,string][]=[['articles','Articles'],['events','Events'],['sources','Sources'],['llm','LLM Queue'],['settings','Settings']]; return <nav>{tabs.map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav> }
function CrawlStatus({state}:{state:CrawlState}){ if(!state.message&&!state.error)return null; return <section className={'crawl-status '+(state.error?'error':'')}>{state.error||state.message}</section> }
function FilterBar(p:any){ return <section className="filters"><div className="filter-grid"><input placeholder="Search articles/events" value={p.q} onChange={(e)=>{p.setQ(e.target.value);p.setPage(1)}}/><select value={p.eventType} onChange={e=>{p.setEventType(e.target.value);p.setPage(1)}}><option value="">Event type</option>{['fed','macro','earnings','guidance','sec_filing','regulation','inflation','rates','company_news','other'].map(x=><option key={x}>{x}</option>)}</select><select value={p.impact} onChange={e=>{p.setImpact(e.target.value);p.setPage(1)}}><option value="">Impact</option>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Source key" value={p.source} onChange={e=>{p.setSource(e.target.value);p.setPage(1)}}/><input placeholder="Ticker" value={p.ticker} onChange={e=>{p.setTicker(e.target.value);p.setPage(1)}}/><label className="fresh"><input type="checkbox" checked={p.fresh} onChange={e=>{p.setFresh(e.target.checked);p.setPage(1)}}/> Fresh only</label></div><div className="pager"><button onClick={()=>p.setPage(Math.max(1,p.page-1))}>‹</button><span>Page {p.page}</span><button onClick={()=>p.setPage(p.page+1)}>›</button></div></section> }
function Articles({filters,refreshKey,onSelect}:{filters:any;refreshKey:number;onSelect:(x:Article)=>void}){ const [data,setData]=useState<any>({items:[]}); const [err,setErr]=useState(''); useEffect(()=>{setErr(''); getJSON('/api/articles?'+qs(filters)).then(setData).catch(e=>setErr(String(e)))},[JSON.stringify(filters),refreshKey]); if(err) return <ErrorState err={err}/>; if(!data.items?.length) return <EmptyState title="No fresh articles"/>; return <div className="table-wrap"><table><thead><tr><th>#</th><th>Source</th><th>Published</th><th>Age</th><th>Impact</th><th>Novelty</th><th>Sentiment</th><th>Title / summary</th><th>Event</th><th>Tickers</th><th>Status</th></tr></thead><tbody>{data.items.map((a:Article,i:number)=><tr key={a.id} onClick={()=>onSelect(a)}><td>{i+1}</td><td><Badge text={a.source_key}/></td><td>{date(a.published_at||a.fetched_at)}</td><td className="positive">{age(a.published_at||a.fetched_at)}</td><td><Impact a={a.analysis}/></td><td><Score v={a.analysis?.novelty_score}/></td><td><Badge text={a.analysis?.sentiment||'pending'} kind={sentimentKind(a.analysis?.sentiment)}/></td><td><div className="title-cell"><EventIcon type={a.analysis?.event_type}/><div><b>{a.title}</b><p>{a.analysis?.summary_vi||a.analysis?.summary_en||a.excerpt||summaryFromText(a.content_text)}</p></div></div></td><td><Badge text={a.analysis?.event_type||'pending'}/></td><td>{(a.analysis?.affected_tickers||[]).map(t=><Badge key={t} text={t} kind="ticker"/>)}</td><td><Badge text={a.status}/></td></tr>)}</tbody></table></div> }
function Events({filters,refreshKey,onSelect}:{filters:any;refreshKey:number;onSelect:(x:Cluster)=>void}){ const [data,setData]=useState<any>({items:[]}); useEffect(()=>{getJSON('/api/clusters?'+qs(filters)).then(setData)},[JSON.stringify(filters),refreshKey]); if(!data.items?.length) return <EmptyState title="No active events"/>; return <div className="table-wrap"><table><thead><tr><th>#</th><th>Event</th><th>Impact</th><th>Novelty</th><th>Updated</th><th>Articles</th><th>Updates</th><th>Sources</th><th>Type</th><th>Tickers/Sectors</th></tr></thead><tbody>{data.items.map((c:Cluster,i:number)=><tr key={c.id} onClick={()=>onSelect(c)}><td>{i+1}</td><td><div className="title-cell"><EventIcon type={c.event_type}/><div><b>{c.event_title}</b><p>{c.summary_en||c.summary_vi}</p></div></div></td><td><Score v={c.importance_score}/></td><td><Score v={c.novelty_score}/></td><td>{age(c.last_updated_at)}</td><td>{c.article_count}</td><td className="positive">+{c.update_count}</td><td>{c.source_count}</td><td><Badge text={c.event_type}/></td><td>{[...(c.affected_tickers||[]),...(c.affected_sectors||[])].map(x=><Badge key={x} text={x} kind="ticker"/>)}</td></tr>)}</tbody></table></div> }
function Sources({refreshKey,onCrawl,crawl}:{refreshKey:number;onCrawl:(key:string)=>void;crawl:CrawlState}){ const [d,setD]=useState<any>({items:[]}); useEffect(()=>{getJSON('/api/sources').then(setD)},[refreshKey]); return <div className="table-wrap"><table><thead><tr><th>Source</th><th>Type</th><th>Enabled</th><th>Credibility</th><th>Interval</th><th>Health</th><th>Last run</th><th>Returned</th><th>Raw</th><th>Articles</th><th>Diagnostics</th><th>Error</th><th>Action</th></tr></thead><tbody>{d.items?.map((s:SourceHealth)=><tr key={s.key}><td>{s.name}<p>{s.key}</p></td><td><Badge text={s.type}/></td><td>{String(s.enabled)}</td><td><Score v={s.credibility_score}/></td><td>{s.crawl_interval_minutes}m</td><td><Badge text={s.health}/></td><td>{date(s.last_started_at)}</td><td>{s.last_fetched_count??0}</td><td>{s.last_inserted_raw_count??0}</td><td>{s.last_inserted_article_count??0}</td><td><div><b>{s.last_no_fresh_reason||'—'}</b><p>candidates {s.last_candidate_links??0} · old {s.last_older_than_window_count??0} · rejected {s.last_quality_rejected_count??0}</p></div></td><td>{s.last_error}</td><td><button className="small" disabled={crawl.loading||!s.enabled} onClick={()=>onCrawl(s.key)}>Crawl</button></td></tr>)}</tbody></table></div> }
function LLMQueue({refreshKey}:{refreshKey:number}){ const [d,setD]=useState<any>({counts:{},jobs:[]}); useEffect(()=>{getJSON('/api/jobs/llm').then(setD)},[refreshKey]); return <><div className="stats inline">{Object.entries(d.counts||{}).map(([k,v])=><div className="pill" key={k}><b>{String(v)}</b><span>{k}</span></div>)}</div><div className="table-wrap"><table><thead><tr><th>Job</th><th>Article</th><th>Status</th><th>Attempts</th><th>Next run</th><th>Worker</th><th>Error</th></tr></thead><tbody>{d.jobs?.map((j:any)=><tr key={j.id}><td>{j.id.slice(0,8)}</td><td>{j.article_id.slice(0,8)}</td><td><Badge text={j.status}/></td><td>{j.attempts}/{j.max_attempts}</td><td>{date(j.next_run_at)}</td><td>{j.locked_by}</td><td>{j.last_error}</td></tr>)}</tbody></table></div></> }
function Settings({onCrawl,onRetryLLM,crawl}:{onCrawl:()=>void;onRetryLLM:()=>void;crawl:CrawlState}){ return <section className="panel"><h2>Settings</h2><p>Default freshness window: 72 hours. Crawl cadence: 10 minutes. LLM endpoint: localhost:8317 OpenAI-compatible. Max LLM concurrency: 3.</p><p>The production build can be served directly by the Go server from <code>web/dist</code>, so after <code>npm run build</code> open <code>http://localhost:8080</code>.</p><div className="panel-actions"><button className="primary" disabled={crawl.loading} onClick={onCrawl}>Trigger crawl once</button><button disabled={crawl.loading} onClick={onRetryLLM}>Retry failed LLM</button></div></section> }
function Drawer({item,onClose}:{item:Article|Cluster;onClose:()=>void}){ const isCluster='event_title'in item && !('title'in item); return <aside><button className="close" onClick={onClose}>×</button><div className="drawer-title"><EventIcon type={isCluster?(item as Cluster).event_type:(item as Article).analysis?.event_type}/><h2>{'title'in item?item.title:item.event_title}</h2></div>{isCluster?<EventDetail item={item as Cluster}/>:<ArticleDetail initial={item as Article}/>}</aside> }
function ArticleDetail({initial}:{initial:Article}){ const [a,setArticle]=useState<Article>(initial); const [loading,setLoading]=useState(false); const [err,setErr]=useState(''); const [tab,setTab]=useState<DrawerTab>('overview'); useEffect(()=>{let active=true; setLoading(true); setErr(''); getJSON<Article>('/api/articles/'+initial.id).then(x=>{if(active)setArticle(x)}).catch(e=>{if(active)setErr(String(e))}).finally(()=>{if(active)setLoading(false)}); return()=>{active=false}},[initial.id]); const summaryVI=a.analysis?.summary_vi?.trim(); const summaryEN=a.analysis?.summary_en?.trim(); const content=a.content_text?.trim(); return <div><p><Badge text={a.source_key}/> {date(a.published_at||a.fetched_at)} · {age(a.published_at||a.fetched_at)} · {a.word_count??0} words</p>{loading&&<p className="positive">Loading full article detail...</p>}{err&&<p className="error-text">Could not load detail: {err}</p>}{a.canonical_url&&<a href={a.canonical_url} target="_blank">Original URL</a>}<TabButtons tab={tab} setTab={setTab}/>{tab==='overview'&&<div><div className="summary-grid"><section className="summary-box"><h4>Tiếng Việt</h4><p>{summaryVI||'Chưa có tóm tắt tiếng Việt.'}</p></section><section className="summary-box"><h4>English</h4><p>{summaryEN||'No English summary yet.'}</p></section></div><div className="score-grid"><Metric label="Importance" v={a.analysis?.importance_score}/><Metric label="Novelty" v={a.analysis?.novelty_score}/><Metric label="Confidence" v={a.analysis?.confidence}/></div><div className="facts-grid"><section><h3>Key facts</h3><ul className="fancy-list">{asList(a.analysis?.key_facts).map((x,i)=><li key={i}>{x}</li>)}</ul></section><section><h3>New information</h3><ul className="fancy-list">{asList(a.analysis?.new_information).map((x,i)=><li key={i}>{x}</li>)}</ul></section></div><h3>Cluster</h3><p>{a.cluster?.event_title||'No cluster yet'} {a.cluster?.relation&&`· ${a.cluster.relation}`}</p>{a.processing_error&&<p className="error-text">Processing error: {a.processing_error}</p>}</div>}{tab==='content'&&<div><h3>Nội dung gốc</h3>{content?<div className="article-text">{content}</div>:<p>{a.excerpt||'Chưa có nội dung đầy đủ cho tin này. Hãy bấm Crawl now để lấy dữ liệu mới và chờ LLM xử lý nếu cần tóm tắt.'}</p>}</div>}{tab==='json'&&<details open><summary>Raw LLM JSON</summary><pre>{JSON.stringify(a.analysis?.raw_json,null,2)}</pre></details>}</div> }
function EventDetail({item}:{item:Cluster}){ const [d,setD]=useState<any|null>(null); useEffect(()=>{getJSON('/api/clusters/'+item.id).then(setD)},[item.id]); return <div><div className="score-grid"><Metric label="Impact" v={item.importance_score}/><Metric label="Novelty" v={item.novelty_score}/><Metric label="Sources" v={Math.min(100,item.source_count*10)}/></div><section className="summary-box"><p>{item.summary_en||item.summary_vi||'No event summary yet.'}</p></section><h3>Timeline</h3><div className="timeline">{(d?.updates||[]).length?d.updates.map((u:any)=><div className="timeline-item" key={u.id}><div className={'timeline-dot '+deltaKind(u.importance_delta)}/><div><b>{date(u.created_at)} <span className={u.importance_delta>=0?'positive':'negative'}>{u.importance_delta>=0?'+':''}{u.importance_delta}</span></b><p>{u.update_summary}</p></div></div>):<p>No updates recorded yet.</p>}</div><h3>Articles</h3>{d?.articles?.map((x:any)=><p key={x.article.id}><Badge text={x.relation}/>{x.article.title}</p>)}</div> }
function TabButtons({tab,setTab}:{tab:DrawerTab;setTab:(t:DrawerTab)=>void}){ const tabs:[DrawerTab,string][]=[['overview','Tổng quan'],['content','Nội dung gốc'],['json','JSON thô']]; return <div className="drawer-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div> }
function EventIcon({type}:{type?:string}){ const t=type||'other'; return <span className={'event-icon '+t} title={t}><svg viewBox="0 0 24 24" aria-hidden="true"><path d={iconPath(t)}/></svg></span> }
function iconPath(type:string){ if(['fed','rates','macro','inflation'].includes(type)) return 'M4 10l8-6 8 6v2H4v-2zm2 4h3v6H6v-6zm5 0h3v6h-3v-6zm5 0h3v6h-3v-6z'; if(['earnings','guidance','company_news'].includes(type)) return 'M4 20V6h5V4h6v2h5v14H4zm4-3h2v-5H8v5zm3 0h2V9h-2v8zm3 0h2v-3h-2v3z'; if(['sec_filing','regulation'].includes(type)) return 'M6 3h9l3 3v15H6V3zm8 1.5V7h2.5L14 4.5zM8 11h8v2H8v-2zm0 4h8v2H8v-2z'; return 'M12 2l2.7 6.8L22 9.3l-5.6 4.7 1.8 7-6.2-3.8L5.8 21l1.8-7L2 9.3l7.3-.5L12 2z' }
function Badge({text,kind}:{text?:string;kind?:string}){ return <span className={'badge '+(kind||text||'')}>{text||'—'}</span> }
function Score({v,label}:{v?:number;label?:string}){ const n=Math.max(0,Math.min(100,v??0)); return <div className="score">{label&&<span>{label}</span>}<b>{n}</b><i style={{width:n+'%'}}/></div> }
function Metric({label,v}:{label:string;v?:number}){ return <div className="metric"><span>{label}</span><Score v={v}/></div> }
function Impact({a}:{a?:Analysis}){ return <Badge text={a?.market_impact||'pending'} kind={a?.market_impact}/> }
function EmptyState({title}:{title:string}){ return <section className="empty">{title}<p>Try disabling Fresh only for debugging outdated retained data, or click Crawl now to fetch the newest items.</p></section> }
function ErrorState({err}:{err:string}){ return <section className="empty error">{err}</section> }
function date(s?:string){ return s?new Date(s).toLocaleString():'—' }
function age(s?:string){ if(!s) return '—'; const m=Math.floor((Date.now()-new Date(s).getTime())/60000); if(m<60)return `${m}m`; const h=Math.floor(m/60); if(h<48)return `${h}h`; return `${Math.floor(h/24)}d` }
function summaryFromText(s?:string){ if(!s)return ''; return s.length>220?s.slice(0,220)+'…':s }
function asList(v:unknown){ if(Array.isArray(v)) return v.map(x=>typeof x==='string'?x:JSON.stringify(x)); if(!v)return []; return [String(v)] }
function sentimentKind(v?:string){ return v?`sentiment-${v}`:'pending' }
function deltaKind(v?:number){ if((v??0)>0)return 'delta-up'; if((v??0)<0)return 'delta-down'; return 'delta-flat' }

createRoot(document.getElementById('root')!).render(<App />)
