import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Tab = 'articles' | 'events' | 'sources' | 'llm' | 'settings'
type Article = { id:string; source_key:string; source_name:string; title:string; excerpt?:string; canonical_url?:string; published_at?:string; fetched_at:string; status:string; is_outdated:boolean; time_confidence:string; analysis?: Analysis; cluster?: {id:string; event_title:string; event_type:string; relation:string; update_count:number}; duplicate?: unknown }
type Analysis = { importance_score:number; novelty_score:number; confidence:number; market_impact:string; sentiment:string; event_type:string; event_title:string; summary_vi:string; summary_en:string; affected_tickers:string[]; affected_sectors:string[]; affected_assets:string[]; key_facts:string[]; new_information:string[]; raw_json:unknown }
type Cluster = { id:string; event_title:string; event_type:string; status:string; importance_score:number; novelty_score:number; affected_tickers:string[]; affected_sectors:string[]; article_count:number; update_count:number; source_count:number; last_updated_at:string; summary_en?:string; summary_vi?:string }
const API = import.meta.env.VITE_API_BASE || ''

async function getJSON<T>(path:string): Promise<T> { const r = await fetch(API + path); if(!r.ok) throw new Error(await r.text()); return r.json() }
function qs(p:Record<string,string|number|boolean|undefined>) { const q = new URLSearchParams(); Object.entries(p).forEach(([k,v])=>{ if(v!==undefined && v!=='' && v!==false) q.set(k,String(v)) }); return q.toString() }

function App(){ const [tab,setTab]=useState<Tab>((new URLSearchParams(location.search).get('tab') as Tab)||'articles'); const [stats,setStats]=useState<any>({}); const [q,setQ]=useState(''); const [fresh,setFresh]=useState(true); const [impact,setImpact]=useState(''); const [eventType,setEventType]=useState(''); const [ticker,setTicker]=useState(''); const [source,setSource]=useState(''); const [page,setPage]=useState(1); const [selected,setSelected]=useState<any|null>(null)
  useEffect(()=>{getJSON('/api/stats').then(setStats).catch(()=>setStats({}))},[])
  useEffect(()=>{ const u=new URL(location.href); u.searchParams.set('tab',tab); history.replaceState(null,'',u)},[tab])
  const filters={q, fresh_only:fresh, impact, event_type:eventType, ticker, source, page, page_size:50}
  return <div className="app"><Header stats={stats}/><Tabs tab={tab} setTab={setTab}/>{(tab==='articles'||tab==='events')&&<FilterBar {...{q,setQ,fresh,setFresh,impact,setImpact,eventType,setEventType,ticker,setTicker,source,setSource,page,setPage}}/>}<main>{tab==='articles'&&<Articles filters={filters} onSelect={setSelected}/>} {tab==='events'&&<Events filters={filters} onSelect={setSelected}/>} {tab==='sources'&&<Sources/>} {tab==='llm'&&<LLMQueue/>} {tab==='settings'&&<Settings/>}</main>{selected&&<Drawer item={selected} onClose={()=>setSelected(null)}/>}</div> }
function Header({stats}:{stats:any}){ return <header><div><h1>MarketSignal</h1><p>Fresh U.S. financial news intelligence · updated every 10m</p></div><div className="stats">{[['Fresh',stats.fresh_articles],['Events',stats.active_events],['High impact',stats.high_impact],['LLM pending',stats.llm_pending],['Source errors',stats.source_errors]].map(([k,v])=><div className="pill" key={k}><b>{v??0}</b><span>{k}</span></div>)}</div></header> }
function Tabs({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){ const tabs:[Tab,string][]=[['articles','Articles'],['events','Events'],['sources','Sources'],['llm','LLM Queue'],['settings','Settings']]; return <nav>{tabs.map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav> }
function FilterBar(p:any){ return <section className="filters"><input placeholder="Search" value={p.q} onChange={(e)=>{p.setQ(e.target.value);p.setPage(1)}}/><select value={p.eventType} onChange={e=>p.setEventType(e.target.value)}><option value="">Event type</option>{['fed','macro','earnings','guidance','sec_filing','regulation','inflation','rates','company_news','other'].map(x=><option key={x}>{x}</option>)}</select><select value={p.impact} onChange={e=>p.setImpact(e.target.value)}><option value="">Impact</option>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Source" value={p.source} onChange={e=>p.setSource(e.target.value)}/><input placeholder="Ticker" value={p.ticker} onChange={e=>p.setTicker(e.target.value)}/><label className="fresh"><input type="checkbox" checked={p.fresh} onChange={e=>p.setFresh(e.target.checked)}/> Fresh only</label><div className="pager"><button onClick={()=>p.setPage(Math.max(1,p.page-1))}>‹</button><span>Page {p.page}</span><button onClick={()=>p.setPage(p.page+1)}>›</button></div></section> }
function Articles({filters,onSelect}:{filters:any;onSelect:(x:any)=>void}){ const [data,setData]=useState<any>({items:[]}); const [err,setErr]=useState(''); useEffect(()=>{getJSON('/api/articles?'+qs(filters)).then(setData).catch(e=>setErr(String(e)))},[JSON.stringify(filters)]); if(err) return <ErrorState err={err}/>; if(!data.items?.length) return <EmptyState title="No fresh articles"/>; return <table><thead><tr><th>#</th><th>Source</th><th>Published</th><th>Age</th><th>Impact</th><th>Novelty</th><th>Sentiment</th><th>Title / summary</th><th>Event</th><th>Tickers</th><th>Cluster</th><th>Status</th></tr></thead><tbody>{data.items.map((a:Article,i:number)=><tr key={a.id} onClick={()=>onSelect(a)}><td>{i+1}</td><td><Badge text={a.source_key}/></td><td>{date(a.published_at||a.fetched_at)}</td><td className="positive">{age(a.published_at||a.fetched_at)}</td><td><Impact a={a.analysis}/></td><td><Score v={a.analysis?.novelty_score}/></td><td><Badge text={a.analysis?.sentiment||'pending'}/></td><td><b>{a.title}</b><p>{a.analysis?.summary_en||a.excerpt}</p></td><td><Badge text={a.analysis?.event_type||'pending'}/></td><td>{(a.analysis?.affected_tickers||[]).map(t=><Badge key={t} text={t} kind="ticker"/>)}</td><td>{a.cluster?.event_title||'—'}</td><td><Badge text={a.status}/></td></tr>)}</tbody></table> }
function Events({filters,onSelect}:{filters:any;onSelect:(x:any)=>void}){ const [data,setData]=useState<any>({items:[]}); useEffect(()=>{getJSON('/api/clusters?'+qs(filters)).then(setData)},[JSON.stringify(filters)]); if(!data.items?.length) return <EmptyState title="No active events"/>; return <table><thead><tr><th>#</th><th>Event</th><th>Impact</th><th>Updated</th><th>Articles</th><th>Updates</th><th>Sources</th><th>Type</th><th>Tickers/Sectors</th></tr></thead><tbody>{data.items.map((c:Cluster,i:number)=><tr key={c.id} onClick={()=>onSelect(c)}><td>{i+1}</td><td><b>{c.event_title}</b><p>{c.summary_en}</p></td><td><Score v={c.importance_score}/></td><td>{age(c.last_updated_at)}</td><td>{c.article_count}</td><td className="positive">+{c.update_count}</td><td>{c.source_count}</td><td><Badge text={c.event_type}/></td><td>{[...(c.affected_tickers||[]),...(c.affected_sectors||[])].map(x=><Badge key={x} text={x} kind="ticker"/>)}</td></tr>)}</tbody></table> }
function Sources(){ const [d,setD]=useState<any>({items:[]}); useEffect(()=>{getJSON('/api/sources').then(setD)},[]); return <table><thead><tr><th>Source</th><th>Type</th><th>Enabled</th><th>Cred</th><th>Interval</th><th>Health</th><th>Last run</th><th>Fetched</th><th>Error</th></tr></thead><tbody>{d.items?.map((s:any)=><tr key={s.key}><td>{s.name}<p>{s.key}</p></td><td><Badge text={s.type}/></td><td>{String(s.enabled)}</td><td><Score v={s.credibility_score}/></td><td>{s.crawl_interval_minutes}m</td><td><Badge text={s.health}/></td><td>{date(s.last_started_at)}</td><td>{s.last_fetched_count}</td><td>{s.last_error}</td></tr>)}</tbody></table> }
function LLMQueue(){ const [d,setD]=useState<any>({counts:{},jobs:[]}); useEffect(()=>{getJSON('/api/jobs/llm').then(setD)},[]); return <><div className="stats inline">{Object.entries(d.counts||{}).map(([k,v])=><div className="pill" key={k}><b>{String(v)}</b><span>{k}</span></div>)}</div><table><thead><tr><th>Job</th><th>Article</th><th>Status</th><th>Attempts</th><th>Next run</th><th>Worker</th><th>Error</th></tr></thead><tbody>{d.jobs?.map((j:any)=><tr key={j.id}><td>{j.id.slice(0,8)}</td><td>{j.article_id.slice(0,8)}</td><td><Badge text={j.status}/></td><td>{j.attempts}/{j.max_attempts}</td><td>{date(j.next_run_at)}</td><td>{j.locked_by}</td><td>{j.last_error}</td></tr>)}</tbody></table></> }
function Settings(){ return <section className="panel"><h2>Settings</h2><p>Default freshness window: 72 hours. Crawl cadence: 10 minutes. LLM endpoint: localhost:8317 OpenAI-compatible. Max LLM concurrency: 3.</p><button onClick={()=>fetch('/api/admin/crawl-once',{method:'POST'})}>Trigger crawl once</button><button onClick={()=>fetch('/api/admin/retry-failed-llm',{method:'POST'})}>Retry failed LLM</button></section> }
function Drawer({item,onClose}:{item:any;onClose:()=>void}){ const isCluster='event_title'in item && !('title'in item); return <aside><button className="close" onClick={onClose}>×</button><h2>{item.title||item.event_title}</h2>{isCluster?<EventDetail item={item}/>:<ArticleDetail a={item}/>}</aside> }
function ArticleDetail({a}:{a:Article}){ return <div><p><Badge text={a.source_key}/> {date(a.published_at||a.fetched_at)} · {age(a.published_at||a.fetched_at)}</p>{a.canonical_url&&<a href={a.canonical_url} target="_blank">Original URL</a>}<h3>Summary VI</h3><p>{a.analysis?.summary_vi}</p><h3>Summary EN</h3><p>{a.analysis?.summary_en}</p><div className="grid"><Score label="Impact" v={a.analysis?.importance_score}/><Score label="Novelty" v={a.analysis?.novelty_score}/><Score label="Confidence" v={a.analysis?.confidence}/></div><h3>Key facts</h3><ul>{(a.analysis?.key_facts||[]).map((x:any)=><li key={x}>{String(x)}</li>)}</ul><h3>New information</h3><ul>{(a.analysis?.new_information||[]).map((x:any)=><li key={x}>{String(x)}</li>)}</ul><h3>Cluster</h3><p>{a.cluster?.event_title} · {a.cluster?.relation}</p><details><summary>Raw LLM JSON</summary><pre>{JSON.stringify(a.analysis?.raw_json,null,2)}</pre></details></div> }
function EventDetail({item}:{item:Cluster}){ const [d,setD]=useState<any|null>(null); useEffect(()=>{getJSON('/api/clusters/'+item.id).then(setD)},[item.id]); return <div><Score label="Impact" v={item.importance_score}/><p>{item.summary_en||item.summary_vi}</p><h3>Timeline</h3><ul>{d?.updates?.map((u:any)=><li key={u.id}>{date(u.created_at)} · {u.update_summary}</li>)}</ul><h3>Articles</h3>{d?.articles?.map((x:any)=><p key={x.article.id}><Badge text={x.relation}/>{x.article.title}</p>)}</div> }
function Badge({text,kind}:{text?:string;kind?:string}){ return <span className={'badge '+(kind||text||'')}>{text||'—'}</span> }
function Score({v,label}:{v?:number;label?:string}){ const n=v??0; return <div className="score">{label&&<span>{label}</span>}<b>{n}</b><i style={{width:n+'%'}}/></div> }
function Impact({a}:{a?:Analysis}){ return <Badge text={a?.market_impact||'pending'}/> }
function EmptyState({title}:{title:string}){ return <section className="empty">{title}<p>Try disabling Fresh only for debugging outdated retained data.</p></section> }
function ErrorState({err}:{err:string}){ return <section className="empty error">{err}</section> }
function date(s?:string){ return s?new Date(s).toLocaleString():'—' }
function age(s?:string){ if(!s) return '—'; const m=Math.floor((Date.now()-new Date(s).getTime())/60000); if(m<60)return `${m}m`; const h=Math.floor(m/60); if(h<48)return `${h}h`; return `${Math.floor(h/24)}d` }

createRoot(document.getElementById('root')!).render(<App />)
